### ISSUE TITLE
Writing doubles results in excess precision being written.

### ISSUE THREAD

**Issue by thomas-frantz** [skystrife/cpptoml#95]
So I found this merge that seems to be related to fixing this: https://github.com/skystrife/cpptoml/pull/18/files

I load up this toml:
```toml
[graphics]
gamma = 1.1
```

I load this toml and save this toml doing:
```cpp
auto file = cpptoml::parse_file("in.toml")
std::ofstream out("out.toml", std::ios::trunc | std::ios::out);
out << (*file);
out.close();
```

And it results in this toml being generated:
```toml
[graphics]
	gamma = 1.1000000000000001
```
